#!/usr/bin/python3

import pygame

pygame.init()

screen = pygame.display.set_mode((0, 0), pygame.RESIZABLE)
pygame.display.set_caption("My_osu")
background = pygame.image.load("pic/bonus.jpg")
continuer = 1;

while continuer:
    screen.blit(background, (0, 0))
    for event in pygame.event.get():
        if event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE:
            continuer = 0
        if event.type == pygame.QUIT:
            continuer = 0
    pygame.display.flip()
pygame.quit()