#!/usr/bin/python3

import pygame

pygame.init()

screen = pygame.display.set_mode((0, 0), pygame.RESIZABLE)
pygame.display.set_caption("My_osu")
background = pygame.image.load("pic/4.jpg")
logo = pygame.image.load("logo.png")
menu1 = pygame.image.load("menu1.png")

# class mouse:
#     def __init__(self, x, y):
#         self.x = pygame.mouse.get_pos()[0]
#         self.y = pygame.mouse.get_pos()[1]
#     def display(self):
#         print (self.x, self.y)

def condition_circle():
    ball = 1
    return ball

def check_pos():
    pygame.init()
    if (pygame.mouse.get_pos()[0] >= x and pygame.mouse.get_pos()[0] <= x) and (pygame.mouse.get_pos()[1] >= y and pygame.mouse.get_pos()[1] <= y):
        print("play")
    elif (pygame.mouse.get_pos()[0] >= x and pygame.mouse.get_pos()[0] <= x) and (pygame.mouse.get_pos()[1] >= y and pygame.mouse.get_pos()[1] <= y):
        print("edit")
    elif (pygame.mouse.get_pos()[0] >= x and pygame.mouse.get_pos()[0] <= x) and (pygame.mouse.get_pos()[1] >= y and pygame.mouse.get_pos()[1] <= y):
        print("exit")
        pygame.quit()

def under_menu():
    pygame.init()
    screen.blit(menu1, (750, 355))
    for event in pygame.event.get():
        if event.type == pygame.MOUSEBUTTONDOWN:
            print("x : %d\ny : %d" % (pygame.mouse.get_pos()[0], pygame.mouse.get_pos()[1]))
            # check_pos()

def loop():
    pygame.init()
    run = True
    while run:
        screen.blit(background, (0, 0))
        screen.blit(logo, (800, 350))
        for event in pygame.event.get():
            if event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE:
                run = False
            if event.type == pygame.QUIT:
                run = False
            if event.type == pygame.MOUSEBUTTONDOWN and condition_circle() == 1:
                under_menu()   
            pygame.display.flip()
    pygame.quit()

def main():
    loop()

main()